name: 'Godot HTML5 Export'
description: 'Godot Engine: HTML5 export'
author: 'Simon Dalvai @dulvui'
branding:
  color: red
  icon: upload-cloud

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: '.'
  create-export-preset-cfg:
    description: 'Set true if a simple export_presets.cfg should be created'
    required: false
    default: true
  godot-version:
    description: 'Godot Engine version'
    required: false
    default: '4.0.3'
  
runs:
  using: "composite"
  steps:

    - name: Cache Godot files
      id: cache-godot
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/godot/**
          /usr/local/bin/godot
          ~/.config/godot/**
        key: ${{ runner.os }}-godot-${{ inputs.godot-version }}

    - name: Download and config Godot Engine linux server and templates
      shell: bash
      run: |
        echo Test 1.0
        wget -q https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_linux.x86_64.zip 
        wget -q https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz
        mkdir ~/.cache
        mkdir -p ~/.config/godot
        mkdir -p ~/.local/share/godot/templates/${{ inputs.godot-version }}.stable
        unzip Godot_v${{ inputs.godot-version }}-stable_linux.x86_64.zip 
        mv Godot_v${{ inputs.godot-version }}-stable_linux.x86_64 /usr/local/bin/godot
        unzip Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz
        mv templates/* ~/.local/share/godot/templates/${{ inputs.godot-version }}.stable
        rm -f Godot_v${{ inputs.godot-version }}-stable_linux.x86_64.zip Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz
        echo Test 1.1
        sudo apt install libxcursor-dev
        sudo apt install libxinerama-dev
        sudo apt install libxrandr-dev
        sudo apt install libxi6
        sudo apt install libgl1
        export DISPLAY=":0"
        godot --version
        echo Test 1.2
        echo Test 1.3
    - name: Create export presets config
      if: ${{ inputs.create-export-preset-cfg  == 'true' }}
      shell: bash
      run: |
        echo Test 1
        cp ${{ github.action_path }}/export_presets.cfg ${{ inputs.working-directory }}/export_presets.cfg
        echo Test 2
    - name: Export
      shell: bash
      run: |
        echo Test 3
        godot --headless --path ${{ inputs.working-directory }} --export-debug "Web" ../html5/index.html
        cd html5
        ls
        echo Test 4
